stages:
  preprocess:
    cmd: python src/data_cleaning.py
    deps:
      - data/raw/The_Cancer_data_1500_V2.csv
      - src/data_cleaning.py
    outs:
      - data/processed/cleaned_data.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/cleaned_data.csv
      - src/train.py
    outs:
      - models/best_model.pkl
      - models/scaler.pkl
      - artifacts/results.csv
      - artifacts/results.png
